/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package homework;

import java.util.*;

public class App {

    public static void main(String[] args) {
        System.out.println("Input count of queen");
        Scanner sc = new Scanner(System.in);
        new HillClimbing().run(sc.nextInt());
    }
}
